### ISSUE TITLE
Nowcasting model

### ISSUE THREAD

**Issue by kstaniczek** [AQLT/rjwsacruncher#1]

**Comment by kstaniczek** [comment]
I can't seem to open my nowcasting model from my workspace with the package. Does it support dynamic factor models or is it only for seasonal adjustment?

**Comment by AQLT** [comment]
I didn't see this duplicated issue of an `RJDemetra` issue : https://github.com/jdemetra/rjdemetra/issues/82.
I close it here, it isn't related to `rjwsacruncher`.
Regards
